[build-system]
requires = ["hatch>=0.21.0"]
build-backend = "hatch.backends.poetry.PoetryBackend"

[tool.hatch]
name = "analysis_package"
version = "0.1.0"
description = "building Software assignment"
authors = "Junaid Azam"
email = "junaidfazam@gmail.com"
license = "MIT"
python-requires = ">=3.6"